import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    paddingTop: 30,
    flex: 1,
    backgroundColor: '#A7E2E0',
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  title: {
    fontSize: 32,
    fontWeight: '600',
    color: '#2D5A5A',
    textAlign: 'center',
    marginBottom: 40,
    marginTop: 20,
  },
  moodList: {
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    marginBottom: 40,
  },
  moodButton: {
    width: 65,
    height: 65,
    borderRadius: 32.5,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 8,
  },
  selectedMood: {
    transform: [{ scale: 1.1 }],
  },
  noteContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 20,
    padding: 20,
    marginBottom: 30,
    minHeight: 120,
  },
  textInput: {
    fontSize: 16,
    color: '#666',
    textAlignVertical: 'top',
    flex: 1,
    fontWeight: '400',
  },
  voiceButton: {
    position: 'absolute',
    right: 15,
    bottom: 15,
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  voiceIcon: {
    fontSize: 20,
  },
  locationInputContainer: {
    marginBottom: 20,
    position: 'relative',
  },
  locationInputField: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 18,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  locationInputFieldSelected: {
    borderColor: '#4A9B9B',
    borderWidth: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
  },
  searchIcon: {
    marginRight: 12,
  },
  locationInputPlaceholder: {
    fontSize: 16,
    color: '#4A9B9B',
    fontWeight: '400',
    flex: 1,
  },
  selectedLocationContent: {
    flex: 1,
  },
  selectedLocationTitle: {
    fontSize: 16,
    color: '#2D5A5A',
    fontWeight: '600',
    marginBottom: 2,
  },
  selectedLocationSubtitle: {
    fontSize: 14,
    color: '#666',
    fontWeight: '400',
  },
  selectedLocationContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 20,
    padding: 20,
    marginBottom: 30,
    borderWidth: 1,
    borderColor: 'rgba(74, 155, 155, 0.3)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  locationPinContainer: {
    marginRight: 15,
  },
  locationTextContainer: {
    flex: 1,
  },
  selectedLocationInstruction: {
    fontSize: 14,
    color: '#666',
    fontWeight: '400',
    marginTop: 4,
  },
  selectedLocationAddress: {
    fontSize: 12,
    color: '#888',
    marginTop: 2,
    fontStyle: 'italic',
  },
  changeLocationButton: {
    backgroundColor: 'transparent',
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  changeLocationButtonText: {
    color: '#007AFF',
    fontSize: 16,
    fontWeight: '600',
  },
  locationContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 18,
    marginBottom: 16,
  },
  locationContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  locationIcon: {
    fontSize: 20,
    color: '#4A9B9B',
    marginRight: 12,
  },
  locationText: {
    fontSize: 16,
    color: '#2D5A5A',
    fontWeight: '500',
    marginBottom: 2,
  },
  locationSubtext: {
    fontSize: 14,
    color: '#666',
    fontWeight: '400',
  },
  switch: {
    transform: [{ scaleX: 1.2 }, { scaleY: 1.2 }],
  },
  submitButton: {
    backgroundColor: 'linear-gradient(135deg, #E91E63, #3F51B5)',
    borderRadius: 25,
    paddingVertical: 18,
    alignItems: 'center',
    marginBottom: 130,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  submitButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: '600',
  },
   paramContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 15,
    padding: 15,
    marginBottom: 20,
    borderLeftWidth: 4,
    borderLeftColor: '#4A9B9B',
  },
  paramTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2D5A5A',
    marginBottom: 8,
  },
  paramText: {
    fontSize: 14,
    color: '#666',
    marginBottom: 4,
    fontWeight: '400',
  },
});