import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  gradient: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 18,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  header: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '600',
    textAlign: 'center',
    marginTop:40,
    marginBottom: 8,
    letterSpacing: 1,
  },
  title: {
    marginTop: 20,
    color: '#fff',
    fontSize: 28,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 8,
    lineHeight: 22,
  },
  subtitle: {
    marginTop: 10,
    color: '#b3b3b3',
    fontSize: 18,
    textAlign: 'center',
    marginBottom: 18,
  },
  emojiRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 18,
    gap: 0,
    width: '100%',
  },
  emojiButton: {
    marginHorizontal: 24,
    alignItems: 'center',
  },
  emoji: {
    fontSize: 47,
    opacity: 0.7,
    textShadowColor: 'rgba(0,0,0,0.18)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  emojiSelected: {
    opacity: 1,
    // textShadowColor: '#1ecbe1',
    // textShadowOffset: { width: 0, height: 2 },
    // textShadowRadius: 8,
  },
  noteInput: {
    marginTop: 15,
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: '#fff',
    fontSize: 15,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    width: '100%',
  },
  chemistryCard: {
    marginTop: 20,
    backgroundColor: 'rgba(30, 120, 90, 0.13)',
    borderRadius: 10,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
    // shadowColor: '#000',
    // shadowOffset: { width: 0, height: 2 },
    // shadowOpacity: 0.10,
    // shadowRadius: 8,
    // elevation: 2,
    width: '100%',
    height: '20%',
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    marginRight: 12,
    borderWidth: 1.5,
    borderColor: '#fff',
  },
  chemistryText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 15,
    marginBottom: 6,
  },
  friendRequestBtn: {
    borderWidth: 1,
    borderColor: '#fff',
    borderRadius: 8,
    paddingVertical: 6,
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.04)',
    marginTop: 2,
  },
  friendRequestText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 15,
  },
//   divider: {
//     height: 1.2,
//     backgroundColor: 'rgba(180,255,255,0.13)',
//     marginVertical: 8,
//     width: '100%',
//     borderRadius: 1,
//   },
  reportBlockContainer: {
    // alignItems: 'center',
    marginTop: 2,
    width: '100%',
  },
  reportBlockLabel: {
    marginTop: 10,
    color: '#b3b3b3',
    fontSize: 21,
    // textAlign: 'center',
    marginBottom: 0,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  safetyAdvice: {
    // marginTop: 10,
    color: '#b3b3b3',
    fontSize: 16,
    // textAlign: 'center',
    marginBottom: 8,
    fontWeight: '400',
    opacity: 0.8,
  },
  reportBlockRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 40,
    marginTop: 20,
    width: '100%',
  },
  reportBlockBtn: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
    marginHorizontal: 18,
    paddingVertical: 2,
    letterSpacing: 0.5,
  },
  NextBtn:{
    // marginTop: 20,
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
    marginHorizontal: 18,
    paddingVertical: 2,
    letterSpacing: 0.5,
  },
  backButton: {
    marginTop: 20,
    position: 'absolute',
    top: 18,
    left: 10,
    zIndex: 10,
  },
  SubmitBtn: {
    // backgroundColor: '#fff',
    color: '#fff',
    textAlign: 'center',
    paddingVertical: 14,
    borderRadius: 8,
    fontWeight: 'bold',
    fontSize: 18,
    marginTop: 16,
    marginBottom: 8,
    // Add shadow for elevation
    // shadowColor: '#000',
    // shadowOffset: { width: 0, height: 2 },
    // shadowOpacity: 0.2,
    // shadowRadius: 2,
    // elevation: 2,
  },
});

export default styles;
