import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  // Select Hug Screen Styles
  container: {
    flex: 1,
    // backgroundColor: '#F3F0FF',
    alignItems: 'center',
    paddingTop: 20,
  },
  backgroundImage: {
  flex: 1,
  width: '100%',
  height: '100%',
},
  header: {
    marginTop: 40,
    width: '100%',
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  appName: {
    fontSize: 26,
    fontWeight: '600',
    color: '#555',
  },
  title: {
    fontSize: 37,
    fontWeight: '700',
    color: '#000',
    marginTop: 10,
  },
  subtitle: {
    fontSize: 21,
    color: '#777',
    marginBottom: 24,
    marginTop: 6,
    textAlign: 'center',
  },
  cardGrid: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 12,
  },
  card: {
    backgroundColor: '#fff',
    width: 140,
    height: 150,
    borderRadius: 16,
    marginHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: '#ccc',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  emoji: {
    fontSize: 28,
    marginBottom: 4,
  },
  cardLabel: {
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 18,
    color: '#000',
  },
  radioRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 24,
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderColor: '#716bff',
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#716bff',
  },
  radioText: {
    fontSize: 14,
    color: '#333',
  },
  buttonWrapper: {
    width: '100%',
  },
  button: {
    borderRadius: 999,
    paddingVertical: 14,
    alignItems: 'center',
  },
  buttonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
  },

  // Choose Recipient Screen Styles
  recipientContainer: {
    flex: 1,
    // backgroundColor: '#f8f7ff',
  },
  recipientHeader: {
    marginTop: 35,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
    // backgroundColor: '#f8f7ff',
  },
  backButton: {
    padding: 5,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 28,
    fontWeight: '600',
    color: '#000',
  },
  headerSpacer: {
    width: 34,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  content: {
    paddingHorizontal: 20,
  },
  recipientTitle: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 8,
    textAlign: 'center',
  },
  recipientSubtitle: {
    fontSize: 22,
    color: '#666',
    marginBottom: 30,
    lineHeight: 22,
    textAlign: 'center',
  },
  tabContainer: {
    flexDirection: 'row',
    marginBottom: 25,
  },
  tab: {
    marginRight: 30,
    paddingBottom: 8,
  },
  activeTab: {
    borderBottomWidth: 2,
    borderBottomColor: '#000',
  },
  tabText: {
    fontSize: 16,
    color: '#999',
    fontWeight: '500',
  },
  activeTabText: {
    color: '#000',
    fontWeight: '600',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 15,
    paddingVertical: 12,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  searchIcon: {
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#000',
  },
  lonelyMessage: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffeef5',
    borderRadius: 12,
    padding: 15,
    marginBottom: 20,
  },
  heartIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#ffb3d1',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  heartEmoji: {
    fontSize: 20,
  },
  lonelyText: {
    fontSize: 14,
    color: '#666',
    lineHeight: 18,
    width:'80%'
  },
  friendsListContainer: {
    paddingBottom: 20,
  },
  friendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 15,
    paddingVertical: 12,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  selectedFriendItem: {
    backgroundColor: '#e8f4fd',
    borderColor: '#4a90e2',
    borderWidth: 1,
  },
  avatar: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    marginRight: 15,
  },
  friendName: {
    flex: 1,
    fontSize: 16,
    fontWeight: '500',
    color: '#000',
  },
  selectedFriendName: {
    color: '#4a90e2',
    fontWeight: '600',
  },
  checkmarkContainer: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#4a90e2',
    justifyContent: 'center',
    alignItems: 'center',
  },
  nextButton: {
    marginBottom:40,
    position: 'absolute',
    bottom: 30,
    right: 20,
    backgroundColor: '#4a90e2',
    borderRadius: 25,
    paddingHorizontal: 20,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  nextButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginRight: 5,
  },
  nextArrow: {
    marginLeft: 2,
  },

  // Personal Message Screen Styles
  messageContainer: {
    flex: 1,
    // backgroundColor: '#F5F3FF',
  },
  messageHeader: {
    marginTop: 50,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 20,
  },
  messageContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  messageTitle: {
    fontSize: 38,
    fontWeight: '700',
    color: '#111827',
    textAlign: 'center',
    marginBottom: 8,
  },
  messageSubtitle: {
    fontSize: 25,
    color: '#6B7280',
    textAlign: 'center',
    fontWeight: '400',
    marginBottom: 32,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 16,
    fontSize: 16,
    color: '#111827',
    marginBottom: 20,
    minHeight: 80,
    borderWidth: 0,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  presetCard: {
    height: 90,
    backgroundColor: '#E0E7FF',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginBottom: 12,
  },
  presetText: {
    fontSize: 16,
    color: '#111827',
    fontWeight: '400',
    lineHeight: 22,
  },
  addEmojiContainer: {
    alignItems: 'center',
    marginVertical: 24,
  },
  addEmoji: {
    color: '#6B7280',
    fontSize: 16,
    fontWeight: '500',
  },

  // Confirmation Screen Styles
  confirmationContainer: {
    flex: 1,
  },
  confirmationSafeArea: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 24,
    justifyContent: 'center',
  },
  confirmationBackButton: {
    position: 'absolute',
    top: 50,
    left: 20,
  },
  confirmationTitle: {
    fontSize: 38,
    fontWeight: '700',
    textAlign: 'center',
    color: '#000',
    marginBottom: 20,
    marginTop: -40,
  },
  heartImagePlaceholder: {
    width: 180,
    height: 180,
    marginBottom: 20,
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderRadius: 90,
  },
  heartPlaceholderText: {
    fontSize: 80,
  },
  characterImage:{
    width: 180,
    height: 180,
  },
  confirmationSubtitle: {
    fontSize: 24,
    fontWeight: '500',
    textAlign: 'center',
    color: '#555',
    marginBottom: 80,
  },
  sendAnotherButton: {
    backgroundColor: '#7D75FF',
    paddingVertical: 16,
    paddingHorizontal: 40,
    borderRadius: 999,
    marginBottom: 16,
    width: '100%',
  },
  sendAnotherButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  dashboardButton: {
    backgroundColor: '#fff',
    paddingVertical: 16,
    paddingHorizontal: 40,
    borderRadius: 999,
    borderColor: '#ccc',
    borderWidth: 1,
    width: '100%',
  },
  dashboardButtonText: {
    color: '#000',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
});