import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#B8E6E1',
  },
  header: {
    marginTop: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#B8E6E1',
  },
  backButton: {
    padding: 4,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  headerRight: {
    width: 32,
  },
  scrollView: {
    flex: 1,
    paddingHorizontal: 16,
  },
  mainContentContainer: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
    marginTop: 10,
    ...(Platform.OS === 'ios' && {
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: -2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 8,
    }),
    ...(Platform.OS === 'android' && {
      elevation: 8,
    }),
  },
  section: {
    marginBottom: 24,
  },
  eventTypeContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingVertical: 20,
    paddingHorizontal: 8,
    marginTop: 10,
    marginHorizontal: 0,
  },
  horizontalScrollContainer: {
    paddingHorizontal: 8,
    gap: 12,
    alignItems: 'center',
  },
  eventTypeWrapper: {
    alignItems: 'center',
    width: 80,
    marginHorizontal: 2,
  },
  eventTypeItem: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  eventTypeText: {
    textAlign: 'center',
    lineHeight: 13,
    maxWidth: 80,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
  },
  selectedEventContainer: {
    backgroundColor: '#E8F0F2',
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 0,
  },
  eventTitleInput: {
    fontSize: 16,
    color: '#333',
    fontWeight: '500',
    flex: 1,
    padding: 0,
    margin: 0,
  },
  selectedEventText: {
    fontSize: 16,
    color: '#333',
    fontWeight: '500',
  },
  moodScrollContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 4,
    marginHorizontal: 0,
  },
  moodScrollContent: {
    paddingHorizontal: 12,
    gap: 12,
    alignItems: 'center',
  },
  moodContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  moodTag: {
    backgroundColor: '#E0E0E0',
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginRight: 0,
    marginBottom: 0,
    minWidth: 80,
    alignItems: 'center',
    justifyContent: 'center',
    ...(Platform.OS === 'ios' && {
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.1,
      shadowRadius: 2,
    }),
    ...(Platform.OS === 'android' && {
      elevation: 2,
    }),
  },
  selectedMoodTag: {
    backgroundColor: '#5DBEA3',
    ...(Platform.OS === 'ios' && {
      shadowColor: '#5DBEA3',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
    }),
    ...(Platform.OS === 'android' && {
      elevation: 4,
    }),
    transform: [{ scale: 1.02 }],
  },
  moodTagText: {
    fontSize: 14,
    color: '#666',
    fontWeight: '500',
    textAlign: 'center',
  },
  selectedMoodTagText: {
    color: '#fff',
    fontWeight: '600',
  },
  optionalText: {
    fontSize: 14,
    color: '#999',
    fontWeight: '400',
  },
  textInput: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    fontSize: 14,
    color: '#333',
    minHeight: 80,
    marginHorizontal: 0,
    textAlignVertical: 'top',
  },
  toggleItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginBottom: 8,
    marginHorizontal: 0,
  },
  toggleLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  toggleText: {
    fontSize: 16,
    color: '#333',
    marginLeft: 12,
  },
  previewContainer: {
    backgroundColor: '#E8F0F2',
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 0,
  },
  previewIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  previewText: {
    flex: 1,
  },
  previewTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
  },
  previewSubtitle: {
    fontSize: 14,
    color: '#666',
    marginTop: 2,
  },
  previewArrow: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  publishButton: {
    backgroundColor: '#5DBEA3',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 40,
  },
  publishButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
});