import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  gradient: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  container: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 32,
    alignItems: 'center',
  },
  header: {
    marginTop: 30,
    color: '#fff',
    fontSize: 20,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 2,
    letterSpacing: 1,
  },
  title: {
    marginTop: 10,
    color: '#fff',
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 18,
    letterSpacing: 0.5,
  },
  card: {
    backgroundColor: 'rgba(20, 40, 60, 0.85)',
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 8,
    elevation: 2,
  },
  cardTitle: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  moodRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    width: '70%',
    alignSelf: 'center',
  },
  emoji: {
    fontSize: 28,
    marginHorizontal: 8,
    opacity: 0.95,
  },
  graphContainer: {
    marginTop: 2,
    marginBottom: 2,
    height: 38,
    width: '100%',
    justifyContent: 'center',
  },
  graphLine: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 28,
    marginHorizontal: 8,
    position: 'relative',
  },
  graphDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#fff',
    position: 'absolute',
    left: 0,
    marginLeft: 0,
  },
  graphSegment: {
    position: 'absolute',
    width: 24,
    height: 2,
    backgroundColor: '#fff',
    borderRadius: 1,
    zIndex: -1,
  },
  graphLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
    marginHorizontal: 8,
  },
  graphLabel: {
    color: '#b3b3b3',
    fontSize: 12,
    fontWeight: '400',
  },
  engagementRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 6,
    marginBottom: 2,
  },
  engagementLabel: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '500',
  },
  engagementValue: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 15,
  },
  suggestionBox: {
    backgroundColor: 'rgba(30, 60, 80, 0.7)',
    borderRadius: 10,
    padding: 10,
    marginTop: 8,
  },
  suggestionText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '400',
  },
  reportRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    alignSelf: 'flex-start',
  },
  reportText: {
    color: '#b3b3b3',
    fontSize: 15,
    fontWeight: '500',
  },
  backButton: {
    marginTop: 20,
    position: 'absolute',
    top: 18,
    left: 10,
    zIndex: 10,
  },
});

export default styles; 