export const moodsData = [
  {
    id: 1,
    name: 'Happy',
    emoji: '😊',
    locations: [
      {
        id: 101,
        name: 'Sunny Park',
        latitude: 37.78825,
        longitude: -122.4324,
        description: 'A peaceful park to uplift your mood',
      },
      {
        id: 102,
        name: 'Joy Gardens',
        latitude: 37.79825,
        longitude: -122.4424,
        description: 'Beautiful garden with colorful flowers',
      },
      {
        id: 103,
        name: 'Happiness Café',
        latitude: 37.77825,
        longitude: -122.4224,
        description: 'Café with positive vibes and great coffee',
      },
      {
        id: 104,
        name: 'Laughter Lounge',
        latitude: 37.78325,
        longitude: -122.4354,
        description: 'Comedy shows and cheerful ambiance',
      },
      {
        id: 105,
        name: 'Happy Vibes Studio',
        latitude: 37.79025,
        longitude: -122.4294,
        description: 'Live music and dance floor to energize your spirit',
      },
    ],
  },
  {
    id: 2,
    name: 'Calm',
    emoji: '🙂',
    locations: [
      {
        id: 201,
        name: 'Tranquil Garden',
        latitude: 37.77825,
        longitude: -122.4124,
        description: 'Peaceful garden for relaxation',
      },
      {
        id: 202,
        name: 'Serenity Spa',
        latitude: 37.78925,
        longitude: -122.4524,
        description: 'Calming spa treatments',
      },
      {
        id: 203,
        name: 'Meditation Center',
        latitude: 37.79725,
        longitude: -122.4224,
        description: 'Group meditation sessions',
      },
      {
        id: 204,
        name: 'Zen Tea House',
        latitude: 37.78125,
        longitude: -122.4374,
        description: 'Quiet tea house with a serene atmosphere',
      },
      {
        id: 205,
        name: 'Ocean Breeze Spot',
        latitude: 37.77525,
        longitude: -122.4284,
        description: 'Relax by the ocean and breathe in the calm',
      },
    ],
  },
  {
    id: 3,
    name: 'Stressed',
    emoji: '🙁',
    locations: [
      {
        id: 301,
        name: 'Relaxation Spa',
        latitude: 37.78425,
        longitude: -122.4624,
        description: 'De-stress with a relaxing massage',
      },
      {
        id: 302,
        name: 'Therapy Center',
        latitude: 37.77625,
        longitude: -122.4524,
        description: 'Professional stress management',
      },
      {
        id: 303,
        name: 'Yoga Studio',
        latitude: 37.79425,
        longitude: -122.4124,
        description: 'Yoga classes for stress relief',
      },
      {
        id: 304,
        name: 'Breathwork Lounge',
        latitude: 37.78225,
        longitude: -122.4184,
        description: 'Guided breathwork for instant relief',
      },
      {
        id: 305,
        name: 'Sound Healing Center',
        latitude: 37.78875,
        longitude: -122.4454,
        description: 'Calm your nerves with sound therapy',
      },
    ],
  },
  {
    id: 4,
    name: 'Lonely',
    emoji: '😔',
    locations: [
      {
        id: 401,
        name: 'Community Center',
        latitude: 37.79925,
        longitude: -122.4324,
        description: 'Join group activities and meet people',
      },
      {
        id: 402,
        name: 'Social Café',
        latitude: 37.78625,
        longitude: -122.4424,
        description: 'Popular café to connect with others',
      },
      {
        id: 403,
        name: 'Book Club',
        latitude: 37.77925,
        longitude: -122.4194,
        description: 'Join discussions and make friends',
      },
      {
        id: 404,
        name: 'Pet Adoption Day',
        latitude: 37.79125,
        longitude: -122.4274,
        description: 'Meet furry friends and make a connection',
      },
      {
        id: 405,
        name: 'Volunteer Hub',
        latitude: 37.77675,
        longitude: -122.4394,
        description: 'Meet people through community volunteering',
      },
    ],
  },
  {
    id: 5,
    name: 'Grateful',
    emoji: '🙏',
    locations: [
      {
        id: 501,
        name: 'Gratitude Garden',
        latitude: 37.78125,
        longitude: -122.4164,
        description: 'Peaceful space for reflection and appreciation',
      },
      {
        id: 502,
        name: 'Thankfulness Temple',
        latitude: 37.79325,
        longitude: -122.4384,
        description: 'Spiritual center for mindful gratitude practice',
      },
      {
        id: 503,
        name: 'Appreciation Café',
        latitude: 37.77725,
        longitude: -122.4244,
        description: 'Community café celebrating daily blessings',
      },
      {
        id: 504,
        name: 'Blessing Bridge',
        latitude: 37.78775,
        longitude: -122.4314,
        description: 'Scenic bridge for contemplating life\'s gifts',
      },
      {
        id: 505,
        name: 'Mindful Meadow',
        latitude: 37.79525,
        longitude: -122.4154,
        description: 'Natural setting for gratitude meditation',
      },
    ],
  },
  {
    id: 6,
    name: 'Sad',
    emoji: '😢',
    locations: [
      {
        id: 601,
        name: 'Comfort Corner',
        latitude: 37.78325,
        longitude: -122.4464,
        description: 'Safe space for emotional support and healing',
      },
      {
        id: 602,
        name: 'Healing Haven',
        latitude: 37.77825,
        longitude: -122.4364,
        description: 'Therapeutic environment for processing emotions',
      },
      {
        id: 603,
        name: 'Support Circle',
        latitude: 37.79225,
        longitude: -122.4264,
        description: 'Group therapy sessions and peer support',
      },
      {
        id: 604,
        name: 'Gentle Grove',
        latitude: 37.78525,
        longitude: -122.4134,
        description: 'Quiet nature spot for solace and reflection',
      },
      {
        id: 605,
        name: 'Renewal Center',
        latitude: 37.77525,
        longitude: -122.4484,
        description: 'Professional counseling and emotional wellness',
      },
    ],
  },
  {
    id: 7,
    name: 'Frustrated',
    emoji: '😤',
    locations: [
      {
        id: 701,
        name: 'Release Room',
        latitude: 37.79125,
        longitude: -122.4344,
        description: 'Safe space to vent and release pent-up energy',
      },
      {
        id: 702,
        name: 'Anger Management Center',
        latitude: 37.78225,
        longitude: -122.4254,
        description: 'Professional help for managing frustration',
      },
      {
        id: 703,
        name: 'Boxing Gym',
        latitude: 37.77925,
        longitude: -122.4434,
        description: 'Physical outlet for releasing frustration',
      },
      {
        id: 704,
        name: 'Scream Sanctuary',
        latitude: 37.78725,
        longitude: -122.4174,
        description: 'Soundproof space for emotional release',
      },
      {
        id: 705,
        name: 'Problem-Solving Plaza',
        latitude: 37.79425,
        longitude: -122.4404,
        description: 'Collaborative space for working through challenges',
      },
    ],
  },
];