import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    safeArea: {
        flex: 1,
    },
    content: {
        flex: 1,
        paddingHorizontal: 20,
        paddingTop: 40,
    },
    title: {
        fontSize: 38,
        fontWeight: 'bold',
        color: 'white',
        lineHeight: 42,
    },
    callout: {
        width: 200,
        padding: 10,
    },
    calloutTitle: {
        fontWeight: 'bold',
        marginBottom: 5,
    },
    calloutDescription: {
        color: '#555',
    },
    subtitle: {
        fontSize: 18,
        color: 'white',
        marginTop: 8,
        opacity: 0.9,
        lineHeight: 22,
    },
    spotsContainer: {
        marginTop: 40,
        gap: 16,
    },
    spotCard: {
        flexDirection: 'row',
        padding: 20,
        borderRadius: 20,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 5,
    },
    iconContainer: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: 'rgba(255, 255, 255, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    textContainer: {
        flex: 1,
    },
    spotTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
        marginBottom: 4,
    },
    spotSubtitle: {
        fontSize: 14,
        color: '#666',
    },
    mapButton: {
        backgroundColor: '#5DCCB9',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
        borderRadius: 30,
        marginTop: 'auto',
        marginBottom: 30,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.2,
        shadowRadius: 5.46,
        elevation: 9,
    },
    mapButtonText: {
        color: 'white',
        fontSize: 18,
        fontWeight: '600',
        marginRight: 8,
    },
    // Map Screen Styles
    mapContainer: {
        flex: 1,
        backgroundColor: '#fff',
    },
    mapHeader: {
        paddingBottom: 20,
    },
    backButton: {
        position: 'absolute',
        left: 20,
        top: 50,
        zIndex: 1,
    },
    mapTitle: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#1A5F5A',
        textAlign: 'center',
        marginTop: 60,
    },
    mapSubtitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1A5F5A',
        textAlign: 'center',
    },
    map: {
        flex: 1,
    },
    markerContainer: {
        minWidth: 500,     
        width: 390,
        paddingVertical: 6,
        paddingHorizontal: 10,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    markerTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        padding: 20,
    },
    markerSubtitle: {
        fontSize: 14,
        color: '#666',
        marginTop: 2,
    },
    markerDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#333',
        marginTop: 8,
    },
    bottomCard: {
        backgroundColor: '#FFF9F2',
        borderRadius: 20,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 3,
        marginBottom: 16,
    },
    cardContent: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    cardTextContainer: {
        flex: 1,
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
        marginBottom: 4,
    },
    cardSubtitle: {
        fontSize: 14,
        color: '#666',
    },
    directionsButton: {
        backgroundColor: '#1A5F5A',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        borderRadius: 25,
    },
    directionsButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '600',
        marginRight: 6,
    },
    mapHeaderGradient: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 170,
        zIndex: 1,
    },
    mapHeaderContainer: {
        flex: 1,
        justifyContent: 'flex-end',
        paddingLeft: 32,
        paddingBottom: 12,
        paddingTop: 48,
    },
    mapHeaderText: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#183A37',
        lineHeight: 32,
    },
    mapBackButton: {
        position: 'absolute',
        top: 50,
        left: 20,
        zIndex: 2,
        borderRadius: 20,
        padding: 8,
    },
    floatingDirectionsButton: {
        position: 'absolute',
        left: 40,
        right: 40,
        bottom: 40,
        backgroundColor: '#004D47',
        borderRadius: 28,
        paddingVertical: 18,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 10,
        shadowColor: '#000',
        shadowOpacity: 0.12,
        shadowRadius: 8,
        elevation: 6,
    },
    floatingDirectionsButtonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 20,
        letterSpacing: 0.2,
    },
    bottomCardContainer: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        paddingHorizontal: 16,
        paddingBottom: 24,
        backgroundColor: 'transparent',
        zIndex: 10,
    },
    getDirectionsButton: {
        backgroundColor: '#004D47',
        borderRadius: 28,
        paddingVertical: 18,
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
    },
    getDirectionsButtonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 20,
        letterSpacing: 0.2,
    },
    // Directions Screen Styles
    directionsScreenContainer: {
        flex: 1,
        backgroundColor: '#FFF9F2',
        paddingHorizontal: 20,
        paddingTop: 48,
    },
    directionsBackButton: {
        position: 'absolute',
        top: 48,
        left: 16,
        zIndex: 2,
        backgroundColor: 'rgba(255,255,255,0.85)',
        borderRadius: 20,
        padding: 8,
    },
    directionsTitleRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 20,
    },
    directionsTitle: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#222',
        marginBottom: 4,
    },
    directionsSubtitle: {
        fontSize: 16,
        color: '#666',
        marginBottom: 2,
    },
    directionsIcon: {
        marginLeft: 10,
        marginTop: 4,
    },
    directionsInfoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    directionsInfoIcon: {
        marginRight: 8,
    },
    directionsInfoText: {
        fontSize: 16,
        color: '#222',
    },
    meditationCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
        marginTop: 20,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    meditationCardTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#222',
        marginBottom: 16,
    },
    meditationCardImage: {
        width: '100%',
        height: 120,
        borderRadius: 12,
        backgroundColor: '#B2DFDB',
        marginBottom: 16,
    },
    meditationTrackRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    meditationTrackTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#222',
    },
    meditationProgressRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
    },
    meditationProgressTime: {
        fontSize: 14,
        color: '#666',
        width: 40,
        textAlign: 'center',
    },
    meditationProgressBarBg: {
        flex: 1,
        height: 6,
        backgroundColor: '#E0E0E0',
        borderRadius: 3,
        marginHorizontal: 12,
        overflow: 'hidden',
    },
    meditationProgressBarFill: {
        width: '20%',
        height: 6,
        backgroundColor: '#4CAF50',
        borderRadius: 3,
    },
    meditationControlsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
    },
    meditationPlayButton: {
        backgroundColor: '#4CAF50',
        borderRadius: 32,
        width: 64,
        height: 64,
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 30,
    },
    startMeditationButton: {
        backgroundColor: '#4CAF50',
        borderRadius: 16,
        paddingVertical: 16,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 8,
    },
    startMeditationButtonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 18,
        letterSpacing: 0.2,
    },
    // Reflection Screen Styles
    reflectionScreenContainer: {
        flex: 1,
        backgroundColor: '#FFF9F2',
    },
    reflectionContent: {
        flex: 1,
        paddingHorizontal: 24,
        paddingTop: 60,
        paddingBottom: 40,
    },
    reflectionTitle: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#222',
        lineHeight: 38,
        marginBottom: 60,
    },
    moodsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 80,
        paddingHorizontal: 10,
    },
    moodButton: {
        alignItems: 'center',
        padding: 10,
    },
    selectedMoodButton: {
        backgroundColor: 'rgba(76, 175, 80, 0.1)',
        borderRadius: 20,
    },
    moodEmoji: {
        fontSize: 48,
        marginBottom: 8,
    },
    moodLabel: {
        fontSize: 16,
        color: '#333',
        fontWeight: '500',
    },
    reflectionInputContainer: {
        backgroundColor: 'white',
        borderRadius: 16,
        marginBottom: 40,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
        position: 'relative',
    },
    reflectionTextInput: {
        padding: 20,
        fontSize: 16,
        color: '#333',
        minHeight: 120,
        textAlignVertical: 'top',
    },
    sendIconButton: {
        position: 'absolute',
        bottom: 16,
        right: 16,
        padding: 8,
    },
    saveReflectionButton: {
        backgroundColor: '#4CAF50',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 18,
        borderRadius: 25,
        marginTop: 'auto',
    },
    saveReflectionButtonText: {
        color: 'white',
        fontSize: 18,
        fontWeight: 'bold',
    },
});